---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"

# elasticsearch is the dns-name of the elasticsearch docker server - this is on the secret internal network!
# dont change it from elasticsearch:9200, as this is the name in docker-compose file
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.enabled: true

#elasticsearch.username: elastic
#elasticsearch.password: changeme

# turn off security a.k.a usernames and passwords
#xpack.security.enabled: false
